CREATE TABLE IF NOT EXISTS areas (
    id SERIAL PRIMARY KEY,
    farm_id INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(255) NOT NULL,
    icon VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
